### ISSUE TITLE
Add swift docker repl command 

### ISSUE THREAD

**Issue by iainsmith** [iainsmith/swift-docker#12]
Add a `swift docker repl` command so it's easy to get a swift repl in a container.

`docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined`

See https://github.com/SwiftDocOrg/DocTest/issues/1 for details

Thanks to @heckj for digging into this.

**Comment by heckj** [comment]
FWIW - this setup is also useful for those cases where you wanted to invoke the tests within LLDB to debug them. I don't know *how* common that use case it, but it's the first tool I lean towards when something is going awry. That said, if a test is failing 90% of the time it's not Linux specific and I can use the macOS debugger to find what I've borked, so this may only apply to that weird corner case that's a Linux specific failure.

The process I've been using to get to LLDB:
- make a one-off dockerfile that loads the sources, tests, and package.swift
- `docker run` with those additional permissions enabled
- `swift test --enable-test-discovery -v` < compiles everything and lets me see where the binary for the tests is
- `lldb .build/...{test target binary}`

**Comment by iainsmith** [comment]
@heckj Do you think we could wrap that all up in?

* `swift docker lldb executable`  - Same as `swift docker lldb`
* `swift docker lldb tests`

**Comment by heckj** [comment]
It definitely might be useful - to be honest, I haven't dug through this codebase, but I'll take a look, as I was thinking I should see how hard it would be to extend this. I really liked using your tool when I was using doctest, and just testing in general - it's super-sweet for the "quick check it" use case.
