### ISSUE TITLE
Detect swift version from manifest file

### ISSUE THREAD

**Issue by mxcl** [iainsmith/swift-docker#3]
I'd be happy to submit the PR, if you agree with the idea.

**Comment by iainsmith** [comment]
Sounds good.

**Comment by iainsmith** [comment]
I also think we can drop swift 4.0 support and target 4.2 & 5.0. Does that simplify this?

**Comment by mxcl** [comment]
Easiest option is to use `swift package dump-package` to get the swift versions, so it doesn’t make much difference.
